; Generated by MiniCompiler
section .text
global main


factorial:
    push rbp
    mov rbp, rsp

L0:
    ; TODO: param
    mov eax, 0
        jmp _epilogue
_epilogue:
    mov rsp, rbp
    pop rbp
    ret

_start:
    call main
    mov rdi, rax
    mov rax, 60
    syscall
