; Generated by MiniCompiler
section .data
malloc_error_msg db 'malloc failed!', 10, 0
bounds_error_msg db 'array index out of bounds!', 10, 0
section .text
extern printf
extern malloc
extern free
extern memcpy
extern exit
global main


factorial:
    push rbp
    mov rbp, rsp
    sub rsp, 16

L0_factorial:
    mov eax, eax
    mov eax, eax
        cmp eax, 1
        jle _cmp_true_1_factorial
        mov eax, 0
        jmp _cmp_end_1_factorial
        _cmp_true_1_factorial:
        mov eax, 1
        _cmp_end_1_factorial:
    cmp eax, 0
        jne L1_factorial
    jmp L2_factorial
L1_factorial:
    mov eax, 1
        jmp _epilogue_factorial
L2_factorial:
    mov eax, eax
    mov eax, eax
    mov eax, eax
        sub eax, 1
    ; TODO: param
    call factorial
    mov eax, eax
        imul eax, eax
    mov eax, eax
        jmp _epilogue_factorial
L3_factorial:
_epilogue_factorial:
    mov rsp, rbp
    pop rbp
    ret

main:
    push rbp
    mov rbp, rsp
    sub rsp, 16

L0_main:
    ; TODO: param
    call factorial
    mov eax, eax
        jmp _epilogue_main
_epilogue_main:
    mov rsp, rbp
    pop rbp
    ret

_start:
    call main
    mov rdi, rax
    mov rax, 60
    syscall