; Generated by MiniCompiler
section .text
global main


main:
    push rbp
    mov rbp, rsp
    sub rsp, 16

L0:
    mov eax, 3
        imul eax, 4
    call malloc
    mov eax, eax
    mov eax, eax
    mov eax, 0
        imul eax, 4
    mov eax, eax
    mov eax, 1
        imul eax, 4
    mov eax, eax
    mov eax, 2
        imul eax, 4
    mov eax, eax
    mov eax, eax
    mov eax, eax
        add eax, eax
    mov eax, eax
    mov eax, eax
        add eax, eax
    mov eax, eax
        jmp _epilogue
_epilogue:
    mov rsp, rbp
    pop rbp
    ret

_start:
    call main
    mov rdi, rax
    mov rax, 60
    syscall
