; Generated by MiniCompiler
section .text
global main


main:
    push rbp
    mov rbp, rsp

L0:
    mov eax, 5
    mov eax, 0
    mov eax, eax
        mov eax, eax
    mov eax, eax
        cmp eax, 0
        jg .Lcmp_true_1
        mov al, 0
        jmp .Lcmp_end_1
        .Lcmp_true_1:
        mov al, 1
        .Lcmp_end_1:
    cmp eax, 0
        jne L1
    jmp L2
L1:
    jmp L3
L2:
    jmp L3
L3:
    mov eax, eax
        mov eax, eax
    mov eax, eax
        jmp .epilogue
.epilogue:
    mov rsp, rbp
    pop rbp
    ret

_start:
    call main
    mov rdi, rax
    mov rax, 60
    syscall
