; Generated by MiniCompiler
section .data
malloc_error_msg db 'malloc failed!', 10, 0
bounds_error_msg db 'array index out of bounds!', 10, 0
section .text
extern printf
extern malloc
extern free
extern memcpy
extern exit
global main


main:
    push rbp
    mov rbp, rsp

L0_main:
    mov eax, 42
    mov eax, eax
    mov eax, eax
        jmp _epilogue_main
_epilogue_main:
    mov rsp, rbp
    pop rbp
    ret

_start:
    call main
    mov rdi, rax
    mov rax, 60
    syscall