; Generated by MiniCompiler
section .text
global main


printf:
    push rbp
    mov rbp, rsp

_epilogue:
    mov rsp, rbp
    pop rbp
    ret

main:
    push rbp
    mov rbp, rsp
    sub rsp, 24

L0:
    ; TODO: param
    ; TODO: param
    ; call printf
            xor eax, eax    ; al = 0 (no vector registers)
            call printf
    mov eax, 0
        jmp _epilogue
_epilogue:
    mov rsp, rbp
    pop rbp
    ret

_start:
    call main
    mov rdi, rax
    mov rax, 60
    syscall
