"""x86-64 code generator from IR - Simplified version for Sprint 5."""

from typing import Dict, List, Optional
from ..ir.ir_instructions import IRInstruction, IRFunction, OpCode, Operand, OperandType
from ..ir.basic_block import BasicBlock
from .abi import ABIConstants


class X86Generator:
    """Generates x86-64 assembly code from IR."""
    
    def __init__(self):
        self.current_function: Optional[IRFunction] = None
        self.var_locations = {}
        self.next_offset = 8
    
    def generate(self, ir_functions: Dict[str, IRFunction]) -> str:
        output = []
        output.append("; Generated by MiniCompiler")
        output.append("section .text")
        output.append("global main")
        output.append("")
        
        for name, func in ir_functions.items():
            output.append(self._generate_function(func))
        
        output.append(self._generate_startup())
        return "\n".join(output)
    
    def _generate_function(self, func: IRFunction) -> str:
        self.current_function = func
        self.var_locations = {}
        self.next_offset = 8
        
        # Allocate stack slots for variables
        self._allocate_slots(func)
        
        lines = [f"\n{func.name}:"]
        lines.append("    push rbp")
        lines.append("    mov rbp, rsp")
        if self.next_offset > 8:
            lines.append(f"    sub rsp, {self.next_offset}")
        lines.append("")
        
        for block in func.blocks:
            if block.label:
                lines.append(f"{str(block.label).replace(':', '')}:")
            for instr in block.instructions:
                asm = self._generate_instruction(instr)
                if asm:
                    for line in asm.split('\n'):
                        lines.append(f"    {line}")
        
        lines.append(".epilogue:")
        lines.append("    mov rsp, rbp")
        lines.append("    pop rbp")
        lines.append("    ret")
        
        return "\n".join(lines)
    
    def _allocate_slots(self, func: IRFunction):
        """Allocate stack slots for variables."""
        vars_set = set()
        
        for block in func.blocks:
            for instr in block.instructions:
                for op in [instr.dest, instr.src1, instr.src2, instr.src3]:
                    if op and op.type == OperandType.VARIABLE:
                        vars_set.add(op.value)
        
        for var in vars_set:
            self.var_locations[var] = self.next_offset
            self.next_offset += 8
    
    def _generate_instruction(self, instr: IRInstruction) -> str:
        op = instr.op
        
        if op == OpCode.ADD:
            return self._gen_binary(instr, "add")
        elif op == OpCode.SUB:
            return self._gen_binary(instr, "sub")
        elif op == OpCode.MUL:
            return self._gen_mul(instr)
        elif op == OpCode.DIV:
            return self._gen_div(instr)
        elif op == OpCode.STORE:
            return self._gen_store(instr)
        elif op == OpCode.LOAD:
            return self._gen_load(instr)
        elif op == OpCode.JUMP:
            return f"jmp {instr.src1}"
        elif op == OpCode.JUMP_IF:
            return self._gen_jump_if(instr)
        elif op == OpCode.RETURN:
            return self._gen_return(instr)
        elif op == OpCode.CALL:
            return self._gen_call(instr)
        
        return f"; TODO: {op.value}"
    
    def _gen_binary(self, instr: IRInstruction, asm_op: str) -> str:
        """Generate binary operation."""
        src1_asm = self._to_asm(instr.src1)
        src2_asm = self._to_asm(instr.src2)
        
        # If src1 is literal, mov it to eax first
        if instr.src1.type == OperandType.LITERAL:
            lines = [f"mov eax, {src1_asm}"]
        else:
            lines = [f"mov eax, {src1_asm}"]
        
        lines.append(f"{asm_op} eax, {src2_asm}")
        
        # Store result if destination is a variable
        if instr.dest and instr.dest.type == OperandType.VARIABLE:
            dest_asm = self._to_asm(instr.dest)
            lines.append(f"mov {dest_asm}, eax")
        
        return "\n    ".join(lines)
    
    def _gen_mul(self, instr: IRInstruction) -> str:
        src1_asm = self._to_asm(instr.src1)
        src2_asm = self._to_asm(instr.src2)
        lines = [f"mov eax, {src1_asm}", f"imul eax, {src2_asm}"]
        
        if instr.dest and instr.dest.type == OperandType.VARIABLE:
            dest_asm = self._to_asm(instr.dest)
            lines.append(f"mov {dest_asm}, eax")
        
        return "\n    ".join(lines)
    
    def _gen_div(self, instr: IRInstruction) -> str:
        src1_asm = self._to_asm(instr.src1)
        src2_asm = self._to_asm(instr.src2)
        lines = [f"mov eax, {src1_asm}", "cdq", f"idiv {src2_asm}"]
        
        if instr.dest and instr.dest.type == OperandType.VARIABLE:
            dest_asm = self._to_asm(instr.dest)
            lines.append(f"mov {dest_asm}, eax")
        
        return "\n    ".join(lines)
    
    def _gen_store(self, instr: IRInstruction) -> str:
        dest_asm = self._to_asm(instr.dest)
        src_asm = self._to_asm(instr.src1)
        
        if instr.src1.type == OperandType.LITERAL:
            return f"mov {dest_asm}, {src_asm}"
        else:
            return f"mov eax, {src_asm}\n    mov {dest_asm}, eax"
    
    def _gen_load(self, instr: IRInstruction) -> str:
        src_asm = self._to_asm(instr.src1)
        dest_asm = self._to_asm(instr.dest)
        return f"mov eax, {src_asm}\n    mov {dest_asm}, eax"
    
    def _gen_jump_if(self, instr: IRInstruction) -> str:
        cond_asm = self._to_asm(instr.dest)
        label = instr.src1
        return f"cmp {cond_asm}, 0\n    jnz {label}"
    
    def _gen_return(self, instr: IRInstruction) -> str:
        if instr.dest:
            dest_asm = self._to_asm(instr.dest)
            return f"mov eax, {dest_asm}\n    jmp .epilogue"
        return "jmp .epilogue"
    
    def _gen_call(self, instr: IRInstruction) -> str:
        func_name = str(instr.src1)
        return f"call {func_name}"
    
    def _to_asm(self, op: Operand) -> str:
        """Convert IR operand to x86-64 assembly string."""
        if op is None:
            return "0"
        
        if op.type == OperandType.LITERAL:
            return str(op.value)
        elif op.type == OperandType.VARIABLE:
            offset = self.var_locations.get(op.value, 8)
            return f"[rbp-{offset}]"
        elif op.type == OperandType.TEMP:
            # Temporary - use eax (value is already there)
            return "eax"
        elif op.type == OperandType.LABEL:
            return str(op).replace(':', '')
        
        return "0"
    
    def _generate_startup(self) -> str:
        return """
_start:
    call main
    mov rdi, rax
    mov rax, 60
    syscall
"""
