"""x86-64 code generator from IR - Extended for Sprint 6 with control flow."""

from typing import Dict, List, Optional
from ..ir.ir_instructions import IRInstruction, IRFunction, OpCode, Operand, OperandType
from ..ir.basic_block import BasicBlock
from .abi import ABIConstants


class X86Generator:
    """Generates x86-64 assembly code from IR."""

    def __init__(self):
        self.current_function: Optional[IRFunction] = None
        self.var_locations = {}
        self.next_offset = 8
        self.label_counter = 0
        self.temp_counter = 0  # Для временных переменных

    def generate(self, ir_functions: Dict[str, IRFunction]) -> str:
        output = []
        output.append("; Generated by MiniCompiler")
        output.append("section .text")
        output.append("global main")
        output.append("")

        for name, func in ir_functions.items():
            output.append(self._generate_function(func))

        output.append(self._generate_startup())
        return "\n".join(output)

    def _generate_function(self, func: IRFunction) -> str:
        self.current_function = func
        self.var_locations = {}
        self.next_offset = 8
        self.temp_counter = 0

        # Allocate stack slots for variables
        self._allocate_slots(func)

        lines = [f"\n{func.name}:"]
        lines.append("    push rbp")
        lines.append("    mov rbp, rsp")
        if self.next_offset > 8:
            lines.append(f"    sub rsp, {self.next_offset}")
        lines.append("")

        for block in func.blocks:
            if block.label:
                # Убираем двоеточие и точки из меток
                label_str = str(block.label).replace(':', '').replace('.', '_')
                lines.append(f"{label_str}:")
            for instr in block.instructions:
                asm = self._generate_instruction(instr)
                if asm:
                    for line in asm.split('\n'):
                        if line.strip():
                            lines.append(f"    {line}")

        lines.append("_epilogue:")
        lines.append("    mov rsp, rbp")
        lines.append("    pop rbp")
        lines.append("    ret")

        return "\n".join(lines)

    def _allocate_slots(self, func: IRFunction):
        """Allocate stack slots for variables."""
        vars_set = set()

        for block in func.blocks:
            for instr in block.instructions:
                for op in [instr.dest, instr.src1, instr.src2, instr.src3]:
                    if op and op.type == OperandType.VARIABLE:
                        vars_set.add(op.value)

        for var in vars_set:
            self.var_locations[var] = self.next_offset
            self.next_offset += 8

    def _generate_instruction(self, instr: IRInstruction) -> str:
        op = instr.op

        if op == OpCode.ADD:
            return self._gen_binary(instr, "add")
        elif op == OpCode.SUB:
            return self._gen_binary(instr, "sub")
        elif op == OpCode.MUL:
            return self._gen_mul(instr)
        elif op == OpCode.DIV:
            return self._gen_div(instr)
        elif op == OpCode.STORE:
            return self._gen_store(instr)
        elif op == OpCode.LOAD:
            return self._gen_load(instr)
        elif op == OpCode.JUMP:
            return f"jmp {instr.src1}"
        elif op == OpCode.JUMP_IF:
            return self._gen_jump_if(instr)
        elif op == OpCode.JUMP_IF_NOT:
            return self._gen_jump_if_not(instr)
        elif op == OpCode.RETURN:
            return self._gen_return(instr)
        elif op == OpCode.CALL:
            return self._gen_call(instr)
        elif op == OpCode.CMP_EQ:
            return self._gen_compare(instr, "je")
        elif op == OpCode.CMP_NE:
            return self._gen_compare(instr, "jne")
        elif op == OpCode.CMP_LT:
            return self._gen_compare(instr, "jl")
        elif op == OpCode.CMP_LE:
            return self._gen_compare(instr, "jle")
        elif op == OpCode.CMP_GT:
            return self._gen_compare(instr, "jg")
        elif op == OpCode.CMP_GE:
            return self._gen_compare(instr, "jge")
        elif op == OpCode.AND:
            return self._gen_logical_and(instr)
        elif op == OpCode.OR:
            return self._gen_logical_or(instr)
        elif op == OpCode.NOT:
            return self._gen_logical_not(instr)

        return f"; TODO: {op.value}"

    def _gen_binary(self, instr: IRInstruction, asm_op: str) -> str:
        """Generate binary operation."""
        src1_asm = self._to_asm(instr.src1)
        src2_asm = self._to_asm(instr.src2)

        lines = []

        # Загружаем первый операнд в eax
        if instr.src1.type == OperandType.LITERAL:
            lines.append(f"mov eax, {src1_asm}")
        elif instr.src1.type == OperandType.VARIABLE:
            lines.append(f"mov eax, {src1_asm}")
        elif instr.src1.type == OperandType.TEMP:
            lines.append(f"mov eax, {src1_asm}")

        # Выполняем операцию
        if instr.src2.type == OperandType.LITERAL:
            lines.append(f"{asm_op} eax, {src2_asm}")
        else:
            lines.append(f"{asm_op} eax, {src2_asm}")

        # Сохраняем результат
        if instr.dest and instr.dest.type == OperandType.VARIABLE:
            dest_asm = self._to_asm(instr.dest)
            lines.append(f"mov {dest_asm}, eax")

        return "\n    ".join(lines)

    def _gen_mul(self, instr: IRInstruction) -> str:
        src1_asm = self._to_asm(instr.src1)
        src2_asm = self._to_asm(instr.src2)
        lines = [f"mov eax, {src1_asm}", f"imul eax, {src2_asm}"]

        if instr.dest and instr.dest.type == OperandType.VARIABLE:
            dest_asm = self._to_asm(instr.dest)
            lines.append(f"mov {dest_asm}, eax")

        return "\n    ".join(lines)

    def _gen_div(self, instr: IRInstruction) -> str:
        src1_asm = self._to_asm(instr.src1)
        src2_asm = self._to_asm(instr.src2)
        lines = [f"mov eax, {src1_asm}", "cdq", f"idiv {src2_asm}"]

        if instr.dest and instr.dest.type == OperandType.VARIABLE:
            dest_asm = self._to_asm(instr.dest)
            lines.append(f"mov {dest_asm}, eax")

        return "\n    ".join(lines)

    def _gen_store(self, instr: IRInstruction) -> str:
        dest_asm = self._to_asm(instr.dest)

        if instr.src1.type == OperandType.LITERAL:
            src_asm = self._to_asm(instr.src1)
            return f"mov {dest_asm}, {src_asm}"
        else:
            src_asm = self._to_asm(instr.src1)
            # Избегаем mov eax, eax
            if src_asm != "eax":
                return f"mov eax, {src_asm}\n    mov {dest_asm}, eax"
            else:
                return f"mov {dest_asm}, eax"

    def _gen_load(self, instr: IRInstruction) -> str:
        src_asm = self._to_asm(instr.src1)
        dest_asm = self._to_asm(instr.dest)

        # Избегаем mov eax, eax
        if src_asm != "eax":
            return f"mov eax, {src_asm}\n    mov {dest_asm}, eax"
        else:
            return f"mov {dest_asm}, eax"

    def _gen_jump_if(self, instr: IRInstruction) -> str:
        """Conditional jump if condition is true (non-zero)."""
        cond_asm = self._to_asm(instr.dest)
        label = str(instr.src1).replace('.', '_')
        return f"cmp {cond_asm}, 0\n    jne {label}"

    def _gen_jump_if_not(self, instr: IRInstruction) -> str:
        """Conditional jump if condition is false (zero)."""
        cond_asm = self._to_asm(instr.dest)
        label = str(instr.src1).replace('.', '_')
        return f"cmp {cond_asm}, 0\n    je {label}"

    def _gen_return(self, instr: IRInstruction) -> str:
        if instr.dest:
            dest_asm = self._to_asm(instr.dest)
            return f"mov eax, {dest_asm}\n    jmp _epilogue"
        return "jmp _epilogue"

    def _gen_call(self, instr: IRInstruction) -> str:
        func_name = str(instr.src1)

        # External calls (printf, malloc, free)
        if func_name in ["printf", "malloc", "free", "scanf"]:
            # System V AMD64 ABI:
            # rdi, rsi, rdx, rcx, r8, r9 - integer/pointer args
            # al = number of vector registers (0 for integer only)
            lines = []
            lines.append(f"; call {func_name}")
            lines.append("    xor eax, eax    ; al = 0 (no vector registers)")

            # For printf, args are already in registers from PARAM instructions
            # We need to load them according to ABI
            # This is simplified - real implementation would collect args from PARAMs
            lines.append(f"    call {func_name}")
            return "\n    ".join(lines)

        return f"call {func_name}"
    def _gen_compare(self, instr: IRInstruction, jump_inst: str) -> str:
        """Generate comparison instruction."""
        self.label_counter += 1
        counter = self.label_counter
        true_label = f"_cmp_true_{counter}"
        end_label = f"_cmp_end_{counter}"

        src1_asm = self._to_asm(instr.src1)
        src2_asm = self._to_asm(instr.src2)

        lines = [
            f"mov eax, {src1_asm}",
            f"cmp eax, {src2_asm}",
            f"{jump_inst} {true_label}",
            f"mov al, 0",
            f"jmp {end_label}",
            f"{true_label}:",
            f"mov al, 1",
            f"{end_label}:",
        ]

        if instr.dest and instr.dest.type == OperandType.VARIABLE:
            dest_asm = self._to_asm(instr.dest)
            lines.append(f"mov {dest_asm}, al")

        return "\n    ".join(lines)

    def _gen_logical_and(self, instr: IRInstruction) -> str:
        """Generate logical AND with short-circuit evaluation."""
        self.label_counter += 1
        counter = self.label_counter
        false_label = f"_land_false_{counter}"
        end_label = f"_land_end_{counter}"

        src1_asm = self._to_asm(instr.src1)
        src2_asm = self._to_asm(instr.src2)

        lines = [
            f"mov al, {src1_asm}",
            f"cmp al, 1",
            f"jne {false_label}",
            f"mov al, {src2_asm}",
            f"cmp al, 1",
            f"jne {false_label}",
            f"mov al, 1",
            f"jmp {end_label}",
            f"{false_label}:",
            f"mov al, 0",
            f"{end_label}:",
        ]

        if instr.dest and instr.dest.type == OperandType.VARIABLE:
            dest_asm = self._to_asm(instr.dest)
            lines.append(f"mov {dest_asm}, al")

        return "\n    ".join(lines)

    def _gen_logical_or(self, instr: IRInstruction) -> str:
        """Generate logical OR with short-circuit evaluation."""
        self.label_counter += 1
        counter = self.label_counter
        true_label = f"_lor_true_{counter}"
        end_label = f"_lor_end_{counter}"

        src1_asm = self._to_asm(instr.src1)
        src2_asm = self._to_asm(instr.src2)

        lines = [
            f"mov al, {src1_asm}",
            f"cmp al, 1",
            f"je {true_label}",
            f"mov al, {src2_asm}",
            f"cmp al, 1",
            f"je {true_label}",
            f"mov al, 0",
            f"jmp {end_label}",
            f"{true_label}:",
            f"mov al, 1",
            f"{end_label}:",
        ]

        if instr.dest and instr.dest.type == OperandType.VARIABLE:
            dest_asm = self._to_asm(instr.dest)
            lines.append(f"mov {dest_asm}, al")

        return "\n    ".join(lines)

    def _gen_logical_not(self, instr: IRInstruction) -> str:
        """Generate logical NOT (negation)."""
        src_asm = self._to_asm(instr.src1)

        lines = [
            f"mov al, {src_asm}",
            f"xor al, 1",
        ]

        if instr.dest and instr.dest.type == OperandType.VARIABLE:
            dest_asm = self._to_asm(instr.dest)
            lines.append(f"mov {dest_asm}, al")

        return "\n    ".join(lines)

    def _to_asm(self, op: Operand) -> str:
        """Convert IR operand to x86-64 assembly string."""
        if op is None:
            return "0"

        if op.type == OperandType.LITERAL:
            if isinstance(op.value, bool):
                return "1" if op.value else "0"
            return str(op.value)
        elif op.type == OperandType.VARIABLE:
            offset = self.var_locations.get(op.value, 8)
            return f"[rbp-{offset}]"
        elif op.type == OperandType.TEMP:
            return "eax"
        elif op.type == OperandType.LABEL:
            return str(op).replace(':', '').replace('.', '_')

        return "0"

    def _generate_startup(self) -> str:
        return """
_start:
    call main
    mov rdi, rax
    mov rax, 60
    syscall
"""