; Generated by MiniCompiler
section .text
global _start

_start:
    call main
    mov rdi, rax
    mov rax, 60
    syscall

main:
    push rbp
    mov rbp, rsp

L0:
    mov eax, 0
    mov eax, 5
    cmp eax, 0
    jne cmp_true_1
    mov al, 0
    jmp cmp_end_1
cmp_true_1:
    mov al, 1
cmp_end_1:
    cmp eax, 0
    je L1
    cdq
    idiv eax
    cmp eax, 2
    jg cmp_true_2
    mov al, 0
    jmp cmp_end_2
cmp_true_2:
    mov al, 1
cmp_end_2:
    cmp eax, 0
    je L1
    mov eax, 1
    jmp L2
L1:
    mov eax, 0
L2:
    cmp eax, 0
    jne L3
    jmp L4
L3:
    mov eax, 1
    jmp epilogue
L4:
    mov eax, 2
    jmp epilogue
epilogue:
    mov rsp, rbp
    pop rbp
    ret
