; Generated by MiniCompiler
section .text
global main


main:
    push rbp
    mov rbp, rsp

L0:
    mov eax, 0
    mov eax, 5
    mov eax, eax
    mov eax, eax
        cmp eax, 0
        jne _cmp_true_1
        mov al, 0
        jmp _cmp_end_1
        _cmp_true_1:
        mov al, 1
        _cmp_end_1:
    cmp eax, 0
        je L1
    mov eax, eax
    mov eax, eax
    mov eax, eax
        cdq
        idiv eax
    mov eax, eax
        cmp eax, 2
        jg _cmp_true_2
        mov al, 0
        jmp _cmp_end_2
        _cmp_true_2:
        mov al, 1
        _cmp_end_2:
    cmp eax, 0
        je L1
    mov eax, 1
    jmp L2
L1:
    mov eax, 0
L2:
    cmp eax, 0
        jne L3
    jmp L4
L3:
    mov eax, 1
        jmp _epilogue
L4:
    mov eax, 2
        jmp _epilogue
L5:
_epilogue:
    mov rsp, rbp
    pop rbp
    ret

_start:
    call main
    mov rdi, rax
    mov rax, 60
    syscall
